# Chart Releaser configuration
# See https://github.com/helm/chart-releaser

# Package configuration
package-path: .cr-release-packages
charts-dir: charts

# Release configuration
release-name-template: "{{ .Name }}-{{ .Version }}"

# Skip charts that don't need independent releases
skip-existing: true

# Generate index
generate-index: true
index-path: index.yaml
pages-branch: gh-pages

# GitHub Pages configuration
packages-with-index: true
