# Chart Releaser configuration
# See https://github.com/helm/chart-releaser

# Owner and repository
owner: CAAPIM
git-repo: apim-charts

# Package configuration
package-path: .cr-release-packages
charts-dir: charts

# Release configuration
release-name-template: "{{ .Name }}-{{ .Version }}"
commit-username: "github-actions[bot]"
commit-email: "github-actions[bot]@users.noreply.github.com"

# Skip charts that don't need independent releases
skip-existing: true

# Generate index
generate-index: true
index-path: index.yaml
pages-branch: gh-pages
