apiVersion: v2
name: ca-api-management
description: CA API Management Suite - Umbrella chart for deploying complete API management stack
type: application
version: 1.0.0
appVersion: "11.1.2"
home: https://github.com/CAAPIM/apim-charts
maintainers:
  - name: Gazza7205
sources:
  - https://github.com/CAAPIM/apim-charts
dependencies:
  - name: gateway
    version: "^3.0.0"
    repository: "file://charts/gateway"
    condition: gateway.enabled
  - name: portal
    version: "^2.3.0"
    repository: "file://charts/portal"
    condition: portal.enabled
  - name: gateway-otk
    version: "^2.0.0"
    repository: "file://charts/gateway-otk"
    condition: gateway-otk.enabled
  - name: druid
    version: "^1.0.0"
    repository: "file://charts/druid"
    condition: druid.enabled
