apiVersion: v2
appVersion: "5.3.3"
description: CA API Developer Portal
name: portal
version: 2.3.16
type: application
home: https://github.com/CAAPIM/apim-charts
maintainers:
  - name: Gazza7205
sources:
  - https://github.com/CAAPIM/apim-charts
dependencies:
- name: druid
  version: ^1.0.0
  condition: portal.analytics.enabled
  repository: "file://../druid"
- name: mysql
  version: 12.2.2
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  condition: global.setupDemoDatabase
- name: rabbitmq
  version: 12.0.3
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  condition: rabbitmq.enabled
- name: ingress-nginx
  repository: "https://kubernetes.github.io/ingress-nginx/"
  version: 4.12.1
  condition: ingress.create
