apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.rabbitmq.loadDefinition.existingSecret}}
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  load_definition.json: |
    {
      "vhosts":[
        {
          "name": "/"
        }
      ],
      "exchanges": [
        {
          "name": "portal-external",
          "vhost": "/",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "portal-internal",
          "vhost": "/",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ]
    }
