name: Release Helm Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release-charts.yml'

permissions:
  contents: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Add required repos
        run: |
          helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
          helm repo add influxdata https://helm.influxdata.com/
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add bitnami-archive https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx/
          helm repo update

      - name: Create gh-pages branch if it doesn't exist
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            echo "Creating gh-pages branch..."
            # Create and push empty gh-pages branch
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Create gh-pages branch"
            git push origin gh-pages
            git checkout -f ${{ github.ref_name }}
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config: .cr.yaml
          charts_dir: charts
          skip_existing: true
